/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ahsan.Faraz (https://sketchfab.com/Ahsan.Faraz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokeball-animated-a1f5d0bac5b74b73adc7d7d1eddc64d3
Title: Pokeball (animated)
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three';

const Pokeball = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/pokeball.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
      if (actions && Object.keys(actions).length > 0) {
        const firstAnimation = Object.keys(actions)[0]; // Get first animation
        const action = actions[firstAnimation];
  
        if (action) {
          action.setLoop(THREE.LoopRepeat); // Set the animation to loop
          action.play();
        }
      }
    }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[Math.PI / 2, 0, 0]} scale={0.5}>
          <group name="ed29bf772abd4e69874694b14dfb0cddfbx" rotation={[-Math.PI, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Camera"
                  position={[7.359, -6.926, 4.958]}
                  rotation={[-Math.PI / 2, 0.756, 2.68]}>
                  <group name="Object_5" />
                </group>
                <group name="Armature">
                  <group name="Object_7">
                    <primitive object={nodes._rootJoint} />
                    <group name="polySurface4" rotation={[Math.PI / 2, 0, 0]}>
                      <mesh
                        name="polySurface4_aiStandardSurface1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.polySurface4_aiStandardSurface1_0.geometry}
                        material={materials.aiStandardSurface1}
                      />
                    </group>
                    <group name="Armature001" position={[0.001, 2.03, 2.096]}>
                      <group name="Object_14">
                        <primitive object={nodes._rootJoint_1} />
                        <group
                          name="polySurface5"
                          position={[-0.001, -2.03, -2.091]}
                          rotation={[Math.PI / 2, 0, 0]}>
                          <mesh
                            name="polySurface5_aiStandardSurface1_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface5_aiStandardSurface1_0.geometry}
                            material={materials.aiStandardSurface1}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Pokeball

useGLTF.preload('/models/pokeball.glb')