/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: pengedarseni (https://sketchfab.com/pengedarseni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-github-logo-441d03d1076b44f483df551e02d970fe
Title: 3D Github Logo
*/

import React, { useRef, useState } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

const GithubLogo = (props) => {
  const { nodes, materials } = useGLTF('/models/github_logo.glb')
  const logoRef = useRef();
  const [hovered,setHovered] = useState(false)

//   useGSAP(() =>{
//     gsap.timeline({
//         repeat:-1,
//         repeatDelay:0.5,
//     }).to(logoRef.current.rotation,{
//         y:hovered? '+=2' : `+=${Math.PI *2}`,
//         x:hovered? '+=2' : `-=${Math.PI *2}`,
//         duration: 2.5,
//         stagger: {
//             each: 0.15,
//         }
//     })
//   })
  return (
        <Float floatIntensity={1}>
            <group {...props} dispose={null}>
            <group position={[-0.055, 2.945, 6.336]} rotation={[Math.PI / 2, 0, 0]} scale={26}>
                <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_4.geometry}
                material={materials.glossy_putih}
                />
                <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_5.geometry}
                material={materials.github}
                />
            </group>
            </group>
    </Float>
  )
}
export default GithubLogo

useGLTF.preload('/models/github_logo.glb')