/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Uriel Bromberg (https://sketchfab.com/UrielBromberg)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/the-sims-plumbob-96c975f02acb41d3b8e485db8ecffd3b
Title: The Sims: Plumbob
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations, Float } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three';

const Plumbob = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/plumbob.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    if (actions && Object.keys(actions).length > 0) {
      const firstAnimation = Object.keys(actions)[0]; // Get first animation
      const action = actions[firstAnimation];

      if (action) {
        action.setLoop(THREE.LoopRepeat); // Set the animation to loop
        action.play();
      }
    }
  }, [actions]); // Run when `actions` are available
  return (
    <Float floatIntensity={1}>
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene" dispose={null}>
        <group
          name="Sketchfab_model"
          position={[-4.756, 0.001, -2.989]}
          rotation={[-Math.PI / 2, 0, -2.426]}>
          <group name="5e3d371ed018467386c2a8f9faaded4efbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Plumbob" rotation={[-Math.PI / 2, 0, 1.486]} scale={100}>
                  <mesh
                    name="Plumbob_Material001_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plumbob_Material001_0.geometry}
                    material={materials['Material.001']}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
    </Float>
  )
}

export default Plumbob;
useGLTF.preload('/models/plumbob.glb')