/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/python-8be4a2579dd84586b915068e475073ee
Title: Python
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

const PythonLogo = (props) => {
  const { nodes, materials } = useGLTF('/models/python_logo.glb')
  return (
    <Float floatIntensity={0.5}>
      <group {...props} dispose={null}>
        <group scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Python_Python_0.geometry}
            material={materials.Python} // Keep original material
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            {/* Modify the original material instead of replacing it */}
            <meshStandardMaterial
              attach="material"
              {...materials.Python} // Keep original colors & textures
              emissive="yellow" // Add glow effect
              emissiveIntensity={0.1}
              roughness={0.3} // Adjust surface reflectiveness
              metalness={0.1} // Increase metallic shine
            />
          </mesh>
        </group>
      </group>
    </Float>
  )
}

export default PythonLogo

useGLTF.preload('/models/python_logo.glb')